development:
  adapter: postgresql
  encoding: unicode
  database: marketplace_development
  pool: 5
  username: marketplace
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: marketplace_test
  pool: 5
  username: marketplace
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: marketplace_production
  pool: 5
  username: marketplace
  password:
